version: '3'

services:
  prometheus-sanduba:
    container_name: prometheus-sanduba
    image: prom/prometheus:v2.30.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
        - sanduba-network
  
  grafana-sanduba:
    container_name: grafana-sanduba
    image: grafana/grafana:8.1.5
    hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    depends_on:
      - prometheus-sanduba
    networks:
        - sanduba-network

  mssql-sanduba:
    container_name: database-sanduba
    hostname: database-sanduba
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    networks:
        - sanduba-network

  api-sanduba:
    container_name: restaurantesanduba.api
    hostname: restaurantesanduba.api
    build:
      context: ../api/RestauranteSanduba
      dockerfile: ../RestauranteSanduba/src/api/Dockerfile
    image: restaurantesanduba.api

    environment:
      ASPNETCORE_URLS: "http://+:9000"
    ports:
      - 5161:9000
    depends_on:
      - mssql-sanduba
      - grafana-sanduba
      - prometheus-sanduba
    networks:
        - sanduba-network

networks:
   sanduba-network:
       driver: bridge